## Multi-annotator {.tabset}

```{r include = FALSE}
require(tidyverse); require(rmarkdown); require(knitr); require(sevenbridges); 

options(max.print = "99"); opts_knit$set(width = 99)
opts_chunk$set(cache=FALSE, tidy=FALSE)

source("../../cgc_auth.R")

```

Portable variant annotation tool developed at NCI.

### base command

```{sh base command, eval=FALSE}

bash multi-annotator.sh

```

### i/o {.tabset}

#### inputs 

```{r inputs}

inputs = list(
  
input(id = "vcf", label = "vcf", description = "vcf", type = "File", cmdInclude=TRUE),
  
input(id = "annotation_databases", label = "annotation_databases", description = "annotation_databases", type = "File...", cmdInclude=TRUE, stageInput="link", secondaryFiles = list(".tbi")),
  
input(id = "reference_fasta", label = "reference_fasta", description = "reference_fasta", type = "File", cmdInclude=TRUE, secondaryFiles = list(".fai")),
  
input(id = "conf_toml", label = "conf_toml", description = "conf_toml", type = "File", cmdInclude=TRUE),
  
input(id = "custom_lua", label = "custom_lua", description = "custom lua for vcfanno", type = "File", cmdInclude=TRUE)

)

```

#### add on scripts {.tabset}

```{sh, eval=FALSE, code=readLines("multi-annotator.sh"), engine='highlight', engine.opts='-S sh'}

```

```{r add on scripts}

multi_annotator_sh = fileDef(name = "multi-annotator.sh", content =
    
Expression(engine = "#cwl-js-engine", 
script = read_file("multi-annotator.sh")))


```

#### outputs

```{r output}

outputs = list(

output(id = "annotation_output_vcf", label = "annotation_output_vcf", 
description = "annotation_output_vcf", type = "File",
inheritMetadataFrom = "#vcf", metadata = list(from_tool = "vcf_multi_annotator"),
glob = Expression(engine = "#cwl-js-engine", 
script = '"*annotated.vcf"')),
  
output(id = "annotation_output_vcf", label = "annotation_output_vcf", 
description = "annotation_output_vcf", type = "File",
inheritMetadataFrom = "#vcf", metadata = list(from_tool = "vcf_multi_annotator"),
glob = Expression(engine = "#cwl-js-engine", 
script = '"*annotated.vcf"')),

output(id = "snpEff_summary", label = "snpEff_summary", 
description = "snpEff_summary", type = "File",
inheritMetadataFrom = "#vcf", metadata = list(from_tool = "vcf_multi_annotator"),
glob = 'snpEff_summary.html'),
  
output(id = "snpEff_genes", label = "snpEff_genes", 
description = "snpEff_genes", type = "File",
inheritMetadataFrom = "#vcf", metadata = list(from_tool = "vcf_multi_annotator"),
glob = 'snpEff_genes.txt')

)


```

### portability {.tabset}

####docker

``` teamcgc/multi-annotator:latest ```

https://hub.docker.com/r/teamcgc/multi-annotator/

####tool definition

```{r 5 create tool object}

tool <- Tool(
id = "VCF multi-annotator", 
label = "VCF multi-annotator",
hints = requirements(docker(pull = "teamcgc/multi-annotator:latest"), cpu(1), mem(1000)),
requirements = requirements(multi_annotator_sh),

baseCommand = "bash multi-annotator.sh",

inputs = inputs,
  
outputs = outputs)

```

####cwl file

```{r eval=create_cwl=="yes"}
write(tool$toJSON(pretty = TRUE), "../apps/multi-annotator.json")
```

####push app to cloud platform

```{r eval=platform_push=="yes"}
project$app_add("multi-annotator", tool)
```

